apiVersion: v1
kind: Service
metadata:
  name: supergateway-service
  namespace: llama-stack-rag
  labels:
    app: supergateway
spec:
  selector:
    app: supergateway
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP